apiVersion: v1
kind: Service
metadata:
  name: sre-app-sre-technical-challenge
  labels:
    app.kubernetes.io/name: {{ include "sre-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}  
  ports:
    - port: {{ .Values.service.port}}  
      targetPort: 8080                 
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sre-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
