replicaCount: 1

image:
  repository: ghcr.io/stordco/sre-technical-challenge
  tag: latest

env:
  DATABASE_URL: postgresql://postgres:password@sre-db-postgresql/sre-technical-challenge
  SECRET_KEY_BASE: GWks+00R99rp4iCigXEDAP7WRQXFiTImOP0vIUmFyaNj1DGDXsMvEfSXtb7ITMKC
  PHX_HOST: localhost
  POOL_SIZE: 10
  PORT: 8080
  PHX_SERVER: true

service:
  type: ClusterIP     # Options: ClusterIP, NodePort, LoadBalancer
  port: 80            # Service port to expose

ingress:
  enabled: false
  
livenessProbe:
  httpGet:
    path: /_health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /_health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
